---
apiVersion: v1
kind: Pod
metadata:
  labels:
  jenkins/invoca-utils: 'true'
  namespace: jenkins
  name: invoca-utils
spec:
  containers:
  - name: ruby
    image: ruby:2.6.5
    tty: true
    resources:
    requests:
      memory: "100Mi"
    command:
      - cat

