---
name: Pipeline

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2, 3.3]
        gemfile:
          - Gemfile
          - gemfiles/activesupport_6_0.gemfile
          - gemfiles/activesupport_6_1.gemfile
          - gemfiles/activesupport_7_0.gemfile
          - gemfiles/activesupport_7_1.gemfile
#          - gemfiles/activesupport_6.gemfile
#          - gemfiles/activesupport_7.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    name: Unit Tests (${{ matrix.ruby }} - ${{ matrix.gemfile }})

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.2.29
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rspec
  build_success:
    if: always()
    needs:
      - tests
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
