---
name: Pipeline

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0', 3.1, 3.2]
        gemfile:
          - Gemfile
          - gemfiles/activesupport_5.gemfile
          - gemfiles/activesupport_6.gemfile
          - gemfiles/activesupport_7.gemfile
        exclude:
          - ruby: 2.5
            gemfile: gemfiles/activesupport_7.gemfile
          - ruby: 2.6
            gemfile: gemfiles/activesupport_7.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    name: Unit Tests (${{ matrix.ruby }} - ${{ matrix.gemfile }})

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.2.29
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rspec
